name: Build Luna Desktop Prod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-prod:
    runs-on: macos-latest
    env:
     APP_PATH: luna-mobile/apps/luna-phone
     APP_ENV: prod
     TAG: LDP
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup GitLab SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: gitlab.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY_GITLAB }}
          private-key-name: gitlab
          
      - name: Install Yalc
        run: sudo npm i -g yalc
        
      - name: Clone and Build Middle Backend
        run: >
          git clone --single-branch --branch ${{ secrets.MIDDLE_BACKEND_BRANCH }} git@gitlab.com:piri/luna-middle-backend-api.git && 
          cd luna-middle-backend-api && yarn && yarn build-electron-${{env.APP_ENV}} &&
          cd build && yalc publish --private
    
      - name: Clone Luna Desktop
        run: >
          git clone --single-branch --branch ${{ secrets.LUNA_DESKTOP_BRANCH }} git@gitlab.com:piri/luna-desktop-electron.git desktop && 
          cd desktop && yalc add luna-middle-backend-ts
          
      - name: Install Dependencies
        run: >
          cd desktop &&
          yarn
          
      - name: Build React
        run: >
          cd desktop &&
          yarn build-react
          
      - name: Build Electron
        run: >
          cd desktop &&
          yarn build-mac
    

